
const express = require("express")
const router = express()


const movei1_router = require("./Movie1.routes")
const movei2_router = require("./Movie2.routes")
const movei3_router = require("./Movie3.routes")
const movei4_router = require("./Movie4.routes")
const movei5_router = require("./Movie5.routes")
const movei6_router = require("./Movie6.routes")
const movei7_router = require("./Movie7.routes")
const movei8_router = require("./Movie8.routes")
const movei9_router = require("./Movie9.routes")
const movei10_router = require("./Movie10.routes")
const movei11_router = require("./Movie11.routes")
const movei12_router = require("./Movie12.routes")
const movei13_router = require("./Movie13.routes")
const movei14_router = require("./Movie14.routes")
const movei15_router = require("./Movie15.routes")
const movei16_router = require("./Movie16.routes")
const movei17_router = require("./Movie17.routes")
const movei18_router = require("./Movie18.routes")
const movei19_router = require("./Movie19.routes")
const movei20_router = require("./Movie20.routes")
const movei21_router = require("./Movie21.routes")
const movei22_router = require("./Movie22.routes")
const movei23_router = require("./Movie23.routes")
const movei24_router = require("./Movie24.routes")
const movei25_router = require("./Movie25.routes")

router.use("/movie",movei1_router)
router.use("/movie2",movei2_router)
router.use("/movie3",movei3_router)
router.use("/movie4",movei4_router)
router.use("/movie5",movei5_router)
router.use("/movie6",movei6_router)
router.use("/movie7",movei7_router)
router.use("/movie8",movei8_router)
router.use("/movie9",movei9_router)
router.use("/movie10",movei10_router)
router.use("/movie11",movei11_router)
router.use("/movie12",movei12_router)
router.use("/movie13",movei13_router)
router.use("/movie14",movei14_router)
router.use("/movie15",movei15_router)
router.use("/movie16",movei16_router)
router.use("/movie17",movei17_router)
router.use("/movie18",movei18_router)
router.use("/movie19",movei19_router)
router.use("/movie20",movei20_router)
router.use("/movie21",movei21_router)
router.use("/movie22",movei22_router)
router.use("/movie23",movei23_router)
router.use("/movie24",movei24_router)
router.use("/movie25",movei25_router)


module.exports = router